name: day12

channels:
  - pytorch # for pytorch components
  - conda-forge
  - defaults

dependencies:
  - numpy # standard imports
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - bokeh
  - ipykernel
  - gensim # NLP imports
  - spacy
  - nltk
  - pytorch
  - torchtext
  - tqdm
  - pip
  - pip:
    - pyldavis
